services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader-2
    ports:
      - "5800:5800"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    volumes:
      - /docker/appdata/jdownloader-2:/config:rw
      - /mnt/disk1/media/Series:/Series:rw
      - /mnt/disk2/media/Films:/Films:rw
    restart: unless-stopped
